'use client';
import NavBar from '@/components/NavBar';
import './globals.css';
import { Inter } from 'next/font/google';
import AuthSession from '@/components/auth/AuthSession';
import { NextUIProvider, createTheme } from '@nextui-org/react';
import { Layout } from '@/components/layout';
import Providers from '@/providers';
import Page from '@/components/page';
import { GlobalModal } from '@/context/GlobalModal';
const myDarkTheme = createTheme({
	type: 'dark',
});
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<NextUIProvider theme={myDarkTheme}>
					<AuthSession>
						<Providers>
							<Page>
								<GlobalModal>
									<Layout>
										<NavBar />
										<div className="h-full w-screen pt-20">{children}</div>
									</Layout>
								</GlobalModal>
							</Page>
						</Providers>
					</AuthSession>
				</NextUIProvider>
			</body>
		</html>
	);
}
